---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: harbor
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting contour"
    kapp.k14s.io/change-rule.1: "delete before deleting contour"
spec:
  serviceAccountName: bootstrap
  syncPeriod: 10m
  fetch:
  - inline:
      paths:
        namespace.yaml: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: harbor
  - helmChart:
      name: harbor
      version: 1.16.1
      repository:
        url: https://helm.goharbor.io
  template:
  - helmTemplate:
      namespace: harbor
      valuesFrom:
      - secretRef:
          name: harbor-values
  deploy:
  - kapp: {}