---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: harbor
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting contour"
    kapp.k14s.io/change-rule.1: "delete before deleting contour"
spec:
  serviceAccountName: bootstrap
  syncPeriod: 10m
  fetch:
  - helmChart:
      name: harbor
      version: 1.16.1
      repository:
        url: https://helm.goharbor.io
  template:
  - helmTemplate:
      namespace: harbor
      valuesFrom:
      - secretRef:
          name: harbor-values
  - ytt:
      inline:
        paths:
          changeconfig.yaml: |
            apiVersion: kapp.k14s.io/v1alpha1
            kind: Config
            minimumRequiredVersion: 0.23.0
            changeGroupBindings:
            - name: harbor-core-changegroup
              resourceMatchers:
              - kindNamespaceNameMatcher: {kind: Deployment, namespace: harbor, name:harbor-core}
          namespace.yaml: |
            ---
            apiVersion: v1
            kind: Namespace
            metadata:
              name: harbor
          secretimport.yaml: |
            ---
            apiVersion: secretgen.carvel.dev/v1alpha1
            kind: SecretImport
            metadata:
              name: wildcard-tls
              namespace: harbor
            spec:
              fromNamespace: projectcontour
          token-secret.yaml: |
            ---
            apiVersion: secretgen.k14s.io/v1alpha1
            kind: Certificate
            metadata:
              name: token-ca-cert
              namespace: harbor
              annotations:
                kapp.k14s.io/change-rule.0: "upsert before upserting harbor-core-changegroup"
            spec:
              isCA: true
            ---
            apiVersion: secretgen.k14s.io/v1alpha1
            kind: Certificate
            metadata:
              name: token-cert
              namespace: harbor
              annotations:
                kapp.k14s.io/change-rule.0: "upsert before upserting harbor-core-changegroup"
            spec:
              caRef:
                name: token-ca-cert
  deploy:
  - kapp: {}