#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-values
type: Opaque
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    # Global variables
    externalURL: https://harbor.local
    harborAdminPassword: (@= data.values.harbor.harborAdminPassword @)
    expose:
      ingress:
        hosts:
          core: harbor.local