#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-values
type: Opaque
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    # Global variables
    externalURL: https://(@= data.values.harbor.hostname @)
    harborAdminPassword: (@= data.values.harbor.harborAdminPassword @)
    core:
      secret: (@= data.values.harbor.core.secret @)
      xsrfKey: (@= data.values.harbor.core.xsrfKey @)
      secretName: token-cert
    jobservice:
      secret: (@= data.values.harbor.jobservice.secret @)
    registry:
      secret: (@= data.values.harbor.registry.secret @)
      credentials:
        password: (@= data.values.harbor.registry.credentials.password @)
        htpasswdString: (@= data.values.harbor.registry.credentials.htpasswdString @)
    expose:
      ingress:
        hosts:
          core: (@= data.values.harbor.hostname @)
      tls:
        certSource: secret
        secret:
          secretName: wildcard-tls
    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: rook-cephfs
          accessMode: ReadWriteMany
          size: 250Gi
        jobservice:
          jobLog:
            storageClass: rook-cephfs
            accessMode: ReadWriteMany