apiVersion: v1
kind: Secret
metadata:
  name: harbor-values
type: Opaque
stringData:
  values.yaml: |
    # Global variables
    externalURL: https://harbor.k8s.local
 
    expose:
      ingress:
        hosts:
          core: harbor.k8s.local