#@ load("@ytt:data", "data")
---
# Git auth for kapp-controller to clone the private conclave repo
apiVersion: v1
kind: Secret
metadata:
  name: conclave-git-auth
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-group: conclave-git-auth
type: Opaque
stringData:
  username: cdelashmutt
  password: #@ data.values.conclave.githubPat
