#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-credentials
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-group: immich-db-credentials
type: kubernetes.io/basic-auth
stringData:
  username: immich
  password: #@ data.values.immich.dbPassword
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: immich-db-credentials
  namespace: bootstrap
spec:
  toNamespace: immich
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-values
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-group: immich-values
type: Opaque
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc
    valkey:
      enabled: true
    server:
      controllers:
        main:
          containers:
            main:
              env:
                DB_HOSTNAME: immich-db-rw
                DB_USERNAME: immich
                DB_PASSWORD: (@= data.values.immich.dbPassword @)
                DB_DATABASE_NAME: immich
      ingress:
        main:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/service.serverstransport: immich-immich-transport@kubernetescrd
          hosts:
          - host: photos.home.grogscave.net
            paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
          tls:
          - secretName: wildcard-tls
            hosts:
            - photos.home.grogscave.net
    machine-learning:
      controllers:
        main:
          containers:
            main:
              env:
                DB_HOSTNAME: immich-db-rw
                DB_USERNAME: immich
                DB_PASSWORD: (@= data.values.immich.dbPassword @)
                DB_DATABASE_NAME: immich
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: persistentVolumeClaim
          accessMode: ReadWriteOnce
          storageClass: longhorn
