---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: kube-vip-cloud-provider
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-group: kube-vip
spec:
  serviceAccountName: bootstrap
  syncPeriod: 10m
  fetch:
  - helmChart:
      name: kube-vip-cloud-provider
      version: "0.2.10"
      repository:
        url: https://kube-vip.github.io/helm-charts
  template:
  - helmTemplate:
      namespace: kube-system
      values:
      - |
        config:
          range-global: 192.168.0.50-192.168.0.59
  - ytt:
      inline:
        paths:
          ip-pool.yaml: |
            ---
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: kube-vip-cloud-provider
              namespace: kube-system
            data:
              range-global: 192.168.0.50-192.168.0.59
          remove-helm-tests.yaml: |
            #@ load("@ytt:overlay", "overlay")
            #@overlay/match by=overlay.subset({"metadata": {"annotations": {"helm.sh/hook": "test"}}}), expects="0+"
            #@overlay/remove
  deploy:
  - kapp: {}
