---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-values
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-group: metallb-values
data:
  values.yaml: |
    speaker:
      frr:
        enabled: false
    frr-k8s:
      prometheus:
        serviceMonitor:
          enabled: false
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: metallb
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-group: metallb
    kapp.k14s.io/change-rule: "upsert after upserting metallb-values"
spec:
  serviceAccountName: bootstrap
  syncPeriod: 10m
  fetch:
  - helmChart:
      name: metallb
      version: "0.16.1"
      repository:
        url: https://metallb.github.io/metallb
  template:
  - helmTemplate:
      namespace: metallb-system
      valuesFrom:
      - configMapRef:
          name: metallb-values
  - ytt:
      inline:
        paths:
          namespace.yaml: |
            ---
            apiVersion: v1
            kind: Namespace
            metadata:
              name: metallb-system
          ip-pool.yaml: |
            ---
            apiVersion: metallb.io/v1beta1
            kind: IPAddressPool
            metadata:
              name: default-pool
              namespace: metallb-system
            spec:
              addresses:
              - 192.168.0.50-192.168.0.59
          l2-advertisement.yaml: |
            ---
            apiVersion: metallb.io/v1beta1
            kind: L2Advertisement
            metadata:
              name: default
              namespace: metallb-system
            spec:
              ipAddressPools:
              - default-pool
              interfaces:
              - eno1
  - ytt:
      inline:
        paths:
          rebase-config.yaml: |
            ---
            apiVersion: kapp.k14s.io/v1alpha1
            kind: Config
            rebaseRules:
            - path: [data]
              type: copy
              sources: [existing]
              resourceMatchers:
              - kindNamespaceNameMatcher:
                  kind: Secret
                  namespace: metallb-system
                  name: metallb-webhook-cert
              - kindNamespaceNameMatcher:
                  kind: Secret
                  namespace: metallb-system
                  name: frr-k8s-webhook-server-cert
  deploy:
  - kapp: {}
