---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: gateway-api
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-group: contour
    kapp.k14s.io/change-rule.0: "upsert after upserting external-mdns"
    kapp.k14s.io/change-rule.1: "delete before deleting external-mdns"

spec:
  serviceAccountName: bootstrap
  syncPeriod: 10m
  fetch:
    - git:
        url: https://github.com/projectcontour/contour
        ref: origin/v1.30.2
        lfsSkipSmudge: true
        subPath: examples
  template:
    - ytt:
        strict: true
        inline:
          paths: 
            overlays/envoy-service-overlay.yaml: |
              #@ load("@ytt:overlay", "overlay")
              #@overlay/match by=overlay.subset({"kind": "Service", "metadata":{"name":"envoy"}})
              ---
              annotations:
                #@overlay/match missing_ok=True
                external-dns.alpha.kubernetes.io/hostname: *.home.grogscave.net
              spec:
                #@overlay/match missing_ok=True
                loadBalancerIP: 192.168.0.50
            # overlays/contour-config.yaml: |
            #   #@ load("@ytt:overlay", "overlay")
            #   #@overlay/match by=overlay.subset({"kind": "ConfigMap", "metadata":{"name":"contour"}})
            #   ---
            #   data:
            #     contour.yaml: |
            #       gateway:
            #         gatewayRef:
            #           name: contour
            #           namespace: projectcontour
        paths:
        # - gateway/00-crds.yaml
        # - gateway/01-gatewayclass.yaml
        # - gateway/02-gateway.yaml
        - contour/
  deploy:
    - kapp: {}