#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: paperless-db-credentials
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-group: paperless-db-credentials
type: kubernetes.io/basic-auth
stringData:
  username: paperless
  password: #@ data.values.paperless.dbPassword
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: paperless-db-credentials
  namespace: bootstrap
spec:
  toNamespace: paperless
---
apiVersion: v1
kind: Secret
metadata:
  name: paperless-values
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-group: paperless-values
type: Opaque
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    env:
      PAPERLESS_DBHOST: paperless-db-rw
      PAPERLESS_DBPORT: "5432"
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: "(@= data.values.paperless.dbPassword @)"
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_URL: https://docs.home.grogscave.net
      PAPERLESS_CSRF_TRUSTED_ORIGINS: https://docs.home.grogscave.net
      PAPERLESS_ALLOWED_HOSTS: "*"
      PAPERLESS_TIME_ZONE: America/New_York
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_CONSUMER_POLLING: "60"
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_MAIL: grog@grogscave.net
      PAPERLESS_ADMIN_PASSWORD: "(@= data.values.paperless.adminPassword @)"
      PAPERLESS_SECRET_KEY: "(@= data.values.paperless.secretKey @)"
    controller:
      strategy: Recreate
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
        - host: docs.home.grogscave.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: wildcard-tls
          hosts:
          - docs.home.grogscave.net
    persistence:
      data:
        enabled: true
        existingClaim: paperless-data-pvc
      media:
        enabled: true
        existingClaim: paperless-media-pvc
      consume:
        enabled: true
        existingClaim: paperless-consume-pvc
      export:
        enabled: true
        existingClaim: paperless-export-pvc
