#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: adguard-password
  namespace: adguard
  annotations:
    kapp.k14s.io/change-group: adguard-password
    kapp.k14s.io/change-rule: "upsert after upserting adguard-namespace"
type: Opaque
stringData:
  password: #@ data.values.adguard.adminPassword
