#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: external-dns
type: Opaque
stringData:
  #@yaml/text-templated-strings
  credentials: |
    [default]
    aws_access_key_id = (@= data.values.externaldns.aws.credentials.accessKey @)
    aws_secret_access_key = (@= data.values.externaldns.aws.credentials.secretKey @)