---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: metallb
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-group: metallb
spec:
  serviceAccountName: bootstrap
  syncPeriod: 10m
  fetch:
    - git:
        url: https://github.com/metallb/metallb
        ref: origin/v0.14.9
        lfsSkipSmudge: true
        subPath: config/manifests
  template:
    - ytt:
        strict: true
        paths:
        - metallb-native.yaml
  deploy:
    - kapp: {}