#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: librechat-values
type: Opaque
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    # Global variables
    global:
      namespaceOverride: librechat
    ingress:
      hosts:
        - host: librechat.home.grogscave.net
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
      - secretName: wildcard-tls
        hosts:
          - librechat.home.grogscave.net
    image:
      repository: ""
      tag: ""
    librechat:
      configYamlContent: |
        version: 1.2.8
        cache: true
        interface:
          customWelcome: "Welcome to the DeLashmutt's Generative AI!"
          mcpServers:
            placeholder: 'MCP Servers'
          endpointsMenu: true
          modelSelect: true
          parameters: true
          sidePanel: true
          prompts: true
          bookmarks: true
          multiConvo: true
          agents: true
          webSearch: true
        registration:
          allowedDomains:
            - "grogscave.net"
        endpoints:
          custom:
            - name: "Ollama"
              apiKey: "Ollama"
              baseURL: "http://chrisdesktop.home:11434/v1/"
              models:
                default: [
                  "llama3.2",
                  "mistral",
                  "codellama",
                  "dolphin-mixtral",
                  "mistral-openorca"
                  ]
                # fetching list of models is supported but the `name` field must start
                # with `ollama` (case-insensitive), as it does in this example.
                fetch: true
              titleConvo: true
              titleModel: "current_model"
              summarize: false
              summaryModel: "current_model"
              forcePrompt: false
              modelDisplayLabel: "Ollama"
          agents:
            capabilities:
            - "execute_code"
            - "file_search"
            - "actions"
            - "tools"
            - "artifacts"
            - "ocr"
            - "chain"
            - "web_search"
        webSearch:
           searxngInstanceUrl: "http://searxng:8888"
           searchProvider: "searxng"
           firecrawlApiKey: "${FIRECRAWL_API_KEY}"
           scraperType: "firecrawl"
           cohereApiKey: "${COHERE_API_KEY}"
           rerankerType: "cohere"
           safeSearch: 1