#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: librechat-values
type: Opaque
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    # Global variables
    ingress:
      hosts:
        - host: librechat.home.grogscave.net
          paths:
            - path: /
              pathType: ImplementationSpecific
    tls:
      - secretName: wildcard-tls
        hosts:
          - librechat.home.grogscave.net
