[k8s]
ubuntu1.home longhorn_disk=nvme0n1 node_ip=192.168.0.136
ubuntu2.home longhorn_disk=nvme0n1 node_ip=192.168.0.194
ubuntu3.home longhorn_disk=nvme0n1 node_ip=192.168.0.228

[k3s_init]
ubuntu1.home

[k3s_join]
ubuntu2.home
ubuntu3.home
