harbor:
    harborAdminPassword: ENC[AES256_GCM,data:buv4e2ikhvf1RRFcE6e3UJUj0Fb9pw==,iv:r49Qw90tRCyFQfGH0i9L1LWVQT2UROuYNy4oDnM6XeU=,tag:W54lUhoU0RiEpKE1i9vZwg==,type:str]
    core:
        secret: ENC[AES256_GCM,data:3P0vH0jHfMzc7fSHUZjM/g==,iv:/h/YheDN571nEnPDyOAtS+d3ncgD2zqtE+aBnDCo7OM=,tag:X28J7e6kOKTtzB2FSnSABg==,type:str]
        xsrfKey: ENC[AES256_GCM,data:yttIfERntb9nIoRGAqs4LoLdqIMakifWbocWkoCyDnA=,iv:OyvEidLyiR4gHpR4DpbeVAylQo6GoiRBzF2N7OpP6Pc=,tag:uxao2uqPcq3QGzxW27IwgQ==,type:str]
    jobservice:
        secret: ENC[AES256_GCM,data:QdvtRh3IWi5l+zI2RiFQqQ==,iv:cSN8QfYF0HmXy5m8hkL+yVvrZp1Lm9tOnHQW5yQkZpo=,tag:QLedG/XnnDzt4DTB2Tz3EQ==,type:str]
    registry:
        secret: ENC[AES256_GCM,data:wX9/gOBTYzJi/MM6cEvloQ==,iv:cm1lbxwRs/vWFD+GOcKC9FPvsH1eBzbfg6QyqOf/lkk=,tag:yZFx/Rybwiu9pBhXeaJT2w==,type:str]
        credentials:
            password: ENC[AES256_GCM,data:Mm85467tJeTNeFNFl3E1M+JO6OGcdMTUdhcLI+n0kzE=,iv:2PQA6Ggfs+A0F+0f0QUPNTHOUtH/Xb1KVIxRzFt/gbs=,tag:kJXZTwLRGkbnYxRj1c7y+w==,type:str]
            htpasswdString: ENC[AES256_GCM,data:z/CL2GqdBdGD/HzDeyYoJpJmppcLYRSAivT7Dh9Hq7uHLVpgpfpdBp5/ZArWEUiBWur5W/4R5K4Sq4uPWBKXh0kqOc2pTzrKFwiT3BD3ZpzT,iv:e7//DoVEcgxReN+k1wZw6j2heuaGQNlVw7E9ml9JuUU=,tag:Y9ElL6+BCfoafmZaG9EC8w==,type:str]
certmanager:
    aws:
        credentials:
            accessKey: ENC[AES256_GCM,data:CUB5/Mx/2o74J3Rhs5T/JG3p7Ec=,iv:evRAWbMYnzJ44L0rSjHKtPUMV7bbJB4Bdyp021N0DDM=,tag:4WG94Bo6gcLKBI/zUxBtwA==,type:str]
            secretKey: ENC[AES256_GCM,data:LSZIylsDaYRb3UoWm1hIrRM629MeWhD23XbN4IWzlWKbBL44zAtNcw==,iv:DehAi+PZ0E52oMuztJcoQXATo7eoovepgokGta4tBMA=,tag:W2InYIIcmxgorC6rajSA9g==,type:str]
externaldns:
    aws:
        credentials:
            accessKey: ENC[AES256_GCM,data:7nN9WPUVLTKSL5Q5uM1j5Zkn+gQ=,iv:Wdhld9dkRcRKq/rr2WewwN4J1Hs2t3DjKZQfBRpXqLY=,tag:/Aty1aY4PSQHK/G3MHUrvA==,type:str]
            secretKey: ENC[AES256_GCM,data:Y25cNU3k52ZnvidbkBR2FFI9Acs1Kd6Ez0KmRtk26OIbLGrZvRl8Kw==,iv:1LHKmBil93RmQmr3V/aDrnyc0Kd71QC2uBufx6L1y2o=,tag:mChZsuMKfafFkuxuo4yeCA==,type:str]
alertmanager:
    smtp:
        password: ENC[AES256_GCM,data:KE29Lep3xxCsccz4Jc/L/Q==,iv:jCXWEOTeP9U9JLYqQJ9ZENRYfar0caRUjCZ8tDzW1ws=,tag:2VdL941MUYrfGJ/5GokMHA==,type:str]
grafana:
    adminPassword: ENC[AES256_GCM,data:U/QOXWi6rR7x,iv:5oEMypLdkDvOlBFFtckicIj3OANM+9NMUwUxKQZzZfQ=,tag:yYEVUGoTfU4JWvkvFNyJ2g==,type:str]
adguard:
    adminPassword: ENC[AES256_GCM,data:oywgdIRIjKdv,iv:VLjqAfxgIz6HgC2WGk4KX+mC4KRCLoqzbb+5kBcXEj4=,tag:Jjt5hBAiw9Nb/2HZ2Pl3lQ==,type:str]
tailscale:
    oauth:
        clientId: ENC[AES256_GCM,data:u4cvQhZLJuqTjZVJXmJSzgM=,iv:80v4DDiUmljfNV2B70YmXgsN/DjB0pLp6uCi3a80YvA=,tag:4uqBCqxxHJLDLKAevSk5vw==,type:str]
        clientSecret: ENC[AES256_GCM,data:ULfSWr8SrhoSbcAAwvQ/BamBsmc3srJkR0NrXg5MAZxDfd229PL3M3LliLjT09KzstJCxgSBRuxDEIanmPrDzA==,iv:ElO3mrisTwtfy08mjR7w2uCWuVBkqAtxdXauG/7om6M=,tag:sTPOu+woCPg2A/XepLMg+Q==,type:str]
immich:
    dbPassword: ENC[AES256_GCM,data:wm9Dk9D7FyqqnATkdo6q4w==,iv:2AkVj5b5THPGtqEX34C12W3E5EQ0gzuYOEdK2tDiaCw=,tag:0JGxXP0GAUzOIrKIsXQxEQ==,type:str]
paperless:
    dbPassword: ENC[AES256_GCM,data:Fs4c9enrwmRhhflGAU2H9Q==,iv://AJqXE+9nNXzvoITJhMzJpDfGjzgK7+AeOVp42irxI=,tag:EYnFksxNXC04HUkzPIebfw==,type:str]
    secretKey: ENC[AES256_GCM,data:ymJWRjuT1rpBy+J1FCcv8YQA2g1C9w4+rcbboJp+8JLHpDr0GGxd2VHqDXnqPmb5QbrCVww3bHZIb/pz+pKUyynPt2I=,iv:xC/7ZxbcVRwGZPt9SasjPt0amoJNR0JjyiqWkdnKheM=,tag:djj63KQgsZnHOFoHBu88Fw==,type:str]
    adminPassword: ENC[AES256_GCM,data:IVdWomn+n/oG,iv:d9MWCABri5EEibjFNkajbhpngw70NgrS4e/S7BzWL5Y=,tag:jz/EHXQe2Z+xStgdsMNSuw==,type:str]
conclave:
    dbPassword: ENC[AES256_GCM,data:ROL+RMM69BTBK3EFTAMzi1HRmsdporwXcyJ3/dcqT7srUu9riQQdnvvtWQ==,iv:Drz8qb4W/liY5vEtwKd9UAwRqLIJ23n3dwmSkk3x1t8=,tag:J2KlmIeYPvqjkg/BAZFNOQ==,type:str]
    #ENC[AES256_GCM,data:DHy5d5Ve6PFtey33vep8iTQ=,iv:50lNLAU5lqjEh2YOMyydCQ8XCcUCPqm4IgfAqfLa7lg=,tag:MjgwOGO1vd2iPUAgNIvHjA==,type:comment]
    jwtSecret: ENC[AES256_GCM,data:jcNpgYXzKNsRQuxAt1PxawNFfgvGe6pqV2/Pf1q69+cQX98H476hWT/J+Ms=,iv:frpH3WIt0SobbNmfM3eWXQv4MicN22gyPPvqwkUaj78=,tag:G82DYP24WRywmQ/ttKOrYw==,type:str]
    smtpUser: ENC[AES256_GCM,data:gYoq2zw6HGGquahyJQ==,iv:7xtP+nsDghOBfdQ6D00j+XYaD/Fff4TIZXXVqgDZCus=,tag:spp51SL5l5X98Wg2sYNhgA==,type:str]
    smtpPassword: ENC[AES256_GCM,data:V/zx3StefZmw3YEGm5S4cg==,iv:gsserVjWfdSPlR+fXJ5VQTMgF6SdKR2LOQK25ndRG/s=,tag:q0za8mV4of78cfQvwAxffQ==,type:str]
    mailHost: ENC[AES256_GCM,data:elW/UttOfGlFwMR150J7/w==,iv:ZZ6JwDf6reUOpUdq7QFOLc1fGIL2iK8ee2/ZqrneYts=,tag:DHjoIZotNL6LfvJlD4LnAQ==,type:str]
    mailPort: ENC[AES256_GCM,data:MIAH,iv:xdUJcS9jiF2Wk2eAITLovRKJnKnqWlVfZ+CtpR77Cug=,tag:8advVNvzHB9xW6moMUZR9Q==,type:int]
    mailFrom: ENC[AES256_GCM,data:ypKPi0ZeTi2CuXAF1FCSQhwn,iv:WLHBoN5lc5AiBJWeUb7gXI/ePiMYf8u9Y8/egwOvTPc=,tag:KRHjzrEc1gTFkLZjxfDfKQ==,type:str]
    #ENC[AES256_GCM,data:uxT+Cg7x6kXiTQvJctnA59VTuePu99W3Q3Fq,iv:qc6WcIQCJ+t8nnga9Mi1GERCMD6r7ni6Vjth4frUouM=,tag:aTo0f/y4bzz5jsdwCQ0/Xw==,type:comment]
    ghcrPat: ENC[AES256_GCM,data:aOJoOr+tMAEsnPDpAPb60xnSlTcFiqYrvjbuhgr+gbHHq0W0iLC38A==,iv:TRaZWcK7WvknNk2UXRkCoxvK21svBZEwacpI6fQlfso=,tag:pepeW6sEA3s1faU29Y4VKQ==,type:str]
    #ENC[AES256_GCM,data:BFvLLcZPHMydHj91tz7aiokjZYeVk2XEGNAbvgPhh7ORZsb5+29GPj/b+AK0h3JuWZqSqTO+,iv:+lbDQFAIgRy7eMEWUL7WkNuHwCOcl9lqMGRbq2KD/zs=,tag:EZgBoTHLK1bY/blJ6p1ApQ==,type:comment]
    githubPat: ENC[AES256_GCM,data:n+oIwTCOKGxySgKmOKcnBKLkzLJytWyrbvoqdRl6c+H/6bC8HAKTdOB9s5DYf0pB1ERJ3IoU46HIFtUBb4y7RiDEMh2tLjH3s7urHfevLaNpOSPZW00xeG28W9F1,iv:ANCMIzxMfAUseBvxbzaFJDa5LHCErV4hENB+VCWjXEY=,tag:2WeF9uJiVFE1H/TIN21DnQ==,type:str]
    allowedEmails: ENC[AES256_GCM,data:JN6h7DiE9UIHX+h3j2SkUtkkCat1nB31oEi+cxDdM9QoKE10tneXQA6RIwOt3THI5MAPFK2/WRPpxHXHBhn9e5XP2LTFieWyNSHRqtc/PVr8,iv:WuYuE8aWSE2fAbd7d+Yy7V67Mpw9OUD3lBfyBGBr7zE=,tag:DR1cD2zHGP358bObKsbRkQ==,type:str]
sops:
    age:
        - recipient: age1p02z2x57jqs7yz476fm03lvkns9arw08ltlg6md5f0da7kpuhgzssn8kkg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMjEvdTdNeDVuRmUyMENX
            M3ZiZGJ5TmtDQ1ZWVDVJb01qL1NLeWpsc1ZNCkVQK2hkd3pMUVdFU29uQlhkK2VI
            eHJLV3E5d1kyZktYNmZyaWRzWFFiRG8KLS0tIDhXOXpnVzhoa1BuMDdSZTJHQ1hX
            OE1xY3JaQVo4cy9DcGJTQWg4bVZ6UzAKK4xc8qcD6TLG2sf20I3Z00JGAQ8P2RNX
            xWpahkHb3jQKMpYJypUkDfQZTrCW04Xv7RhRRlBWJ5Se2rUHvCI0YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T15:12:11Z"
    mac: ENC[AES256_GCM,data:9BbsWUfgyMljenBCgkSOrtvxqPp43rVydtViPITsWezhungRqskATQaPlxk5HOlsptgHhmaByCoFjEYOpplH2E/UuAORWFbXe3lilQfxD8rM1KcxbieF9D6sopTG6rkcwCGUv+EmMTtrtxwZGQKuMSr/ZKg8dNlLYI6XJfIEV8A=,iv:a9MMWERLcCSrHzU0A7sXQL4RyurJCvOA8sWsxGPIbhg=,tag:RkOHG3xySMwQea9yFaqbRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
