---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-values
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-group: monitoring-values
data:
  values.yaml: |
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
        - grafana.home.grogscave.net
        tls:
        - secretName: wildcard-tls
          hosts:
          - grafana.home.grogscave.net
      sidecar:
        datasources:
          enabled: true
    prometheus:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
        - prometheus.home.grogscave.net
        tls:
        - secretName: wildcard-tls
          hosts:
          - prometheus.home.grogscave.net
      prometheusSpec:
        retention: 15d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
        - alertmanager.home.grogscave.net
        tls:
        - secretName: wildcard-tls
          hosts:
          - alertmanager.home.grogscave.net
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: monitoring
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-group: monitoring
    kapp.k14s.io/change-rule: "upsert after upserting monitoring-values"
spec:
  serviceAccountName: bootstrap
  syncPeriod: 10m
  fetch:
  - helmChart:
      name: kube-prometheus-stack
      version: "82.18.0"
      repository:
        url: https://prometheus-community.github.io/helm-charts
  template:
  - helmTemplate:
      namespace: monitoring
      valuesFrom:
      - secretRef:
          name: alertmanager-values
      - configMapRef:
          name: monitoring-values
  - ytt:
      inline:
        paths:
          namespace.yaml: |
            ---
            apiVersion: v1
            kind: Namespace
            metadata:
              name: monitoring
          secretimport.yaml: |
            ---
            apiVersion: secretgen.carvel.dev/v1alpha1
            kind: SecretImport
            metadata:
              name: wildcard-tls
              namespace: monitoring
            spec:
              fromNamespace: cert-manager
          remove-helm-tests.yaml: |
            #@ load("@ytt:overlay", "overlay")
            #@overlay/match by=overlay.subset({"metadata": {"annotations": {"helm.sh/hook": "test"}}}), expects="0+"
            #@overlay/remove
  deploy:
  - kapp: {}
