#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale
  annotations:
    kapp.k14s.io/change-group: tailscale-auth
    kapp.k14s.io/change-rule: "upsert after upserting tailscale-namespace"
type: Opaque
stringData:
  authkey: #@ data.values.tailscale.authKey
