#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secrets
  namespace: bootstrap
  annotations:
    kapp.k14s.io/change-group: tailscale-operator-secrets
type: Opaque
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    oauth:
      clientId: "(@= data.values.tailscale.oauth.clientId @)"
      clientSecret: "(@= data.values.tailscale.oauth.clientSecret @)"
